version: "3"

services:
    app:
        container_name: "cryptoexchange_adminfront"
        image: node:lts-alpine
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - 3000:3000
        working_dir: /app
        tty: true
        command: sh -c "yarn install && yarn start"
